FROM centos:7
MAINTAINER zhongfox

# Install perl and wget
RUN yum -y update && \
    yum -y install git perl wget which curl && \
    yum clean all

RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
RUN yum -y install nodejs

ADD . /projects/node-koa-demo
WORKDIR /projects/node-koa-demo
RUN npm install

EXPOSE 3000
#ENTRYPOINT [ "node", "app.js" ]
